---
- hosts: all
  become: yes
  tasks: 
  - name : i want to installwebserver
    apt: 
      name: apache2
      state: present
   
  - name: install start the server
    service: 
      name: apache2
      state: started

